use warnings;
use strict;
require 'Configuration.pm';
require 'Utils.pm';
require 'Parser.pm';
require 'HostsReportGenerator.pm';
require 'GlobalStatsReportGenerator.pm';
require 'PaginasReportGenerator.pm';
require 'GlobalStats.pm';
require 'ReportWriter.pm';

my $conf = new Configuration();
my $global_stats = new GlobalStats();
my $writer = new ReportWriter();
my @parsers = ();
push (@parsers, new GlobalStatsReportGenerator($conf, $global_stats, $writer));
push (@parsers, new HostsReportGenerator($conf, $global_stats, $writer));
push (@parsers, new PaginasReportGenerator($conf, $global_stats, $writer));
my $parser = new Parser( \@parsers, $conf);
my @files = map {$conf->log_dir.$_} @{Utils->get_files_list($conf->log_dir)};
$parser->parse_files(\@files);